### ISSUE TITLE
Support for 'Mijn lijst'

### ISSUE THREAD

**Issue by wardwygaerts** [add-ons/plugin.video.viervijfzes#68] opened 2021-02-02 11:38 UTC
Is support for 'Mijn lijst' (https://www.goplay.be/mijn-lijst) planned? I use this with VTMGo, VRT Nu & Streamz to easily flag servies/movies we are watching. My widgets are populated with this info.

**Comment by dagwieers** [comment] 2021-02-02 11:40
Duplicate of #53.

**Closed by dagwieers** 2021-02-02 11:40 UTC
